### ISSUE TITLE
todo: make branchless

### ISSUE THREAD

**Issue by MaxBittker** [MaxBittker/glsl-voronoi-noise#2]

**Comment by MaxBittker** [comment]
woops lol, ternaries are still branches :O

**Comment by mootari** [comment]
Looks like this can be closed? 963c23e9a4e8f7b76d0cd91f82f21a42c34c5708

**Comment by MaxBittker** [comment]
tbh, I don't really know enough about shader performance to measure if what I did is faster or not :P
